/// \file include/nauths/saw/blob.hh
/// \file include/nauths/saw/database.hh
/// \file include/nauths/saw/database.hxx
/// \file include/nauths/saw/detail/cache.hh
/// \file include/nauths/saw/detail/cache.hxx
/// \file include/nauths/saw/detail/flag.hh
/// \file include/nauths/saw/detail/flag.hxx
/// \file include/nauths/saw/detail/owner.hh
/// \file include/nauths/saw/detail/proxy.hh
/// \file include/nauths/saw/detail/proxy.hxx
/// \file include/nauths/saw/exceptions.hh
/// \file include/nauths/saw/parameter.hh
/// \file include/nauths/saw/parameter.hxx
/// \file include/nauths/saw/row.hh
/// \file include/nauths/saw/row.hxx
/// \file include/nauths/saw/row_iterator.hh
/// \file include/nauths/saw/saw.hh
/// \file include/nauths/saw/statement.hh
/// \file include/nauths/saw/statement.hxx
/// \file include/nauths/saw/types.hh
/// \file include/nauths/saw/value.hh
/// \file include/nauths/saw/value.hxx
/// \file src/blob.cc
/// \file src/database.cc
/// \file src/error.cc
/// \file src/error.hh
/// \file src/misc/foreach.hh
/// \file src/row.cc
/// \file src/row_iterator.cc
/// \file src/shared/shared_database.cc
/// \file src/shared/shared_database.hh
/// \file src/shared/shared_database.hxx
/// \file src/shared/shared_statement.cc
/// \file src/shared/shared_statement.hh
/// \file src/shared/shared_statement.hxx
/// \file src/statement.cc
/// \file src/value.cc
